version: "3"
services:
  node1:
    build: .
    volumes:
      - .:/opt/server/
    command: [ "python", "-u", "/opt/server/tinyblockchain/app.py", "--config-file", "/opt/server/config/node1.yaml"]
    ports:
      - "5001:5001"
    networks:
      - backend
  node2:
    build: .
    volumes:
      - .:/opt/server/
    command: [ "python", "-u", "/opt/server/tinyblockchain/app.py", "--config-file", "/opt/server/config/node2.yaml"]
    ports:
      - "5002:5002"
    networks:
      - backend
    depends_on:
      - node1
  node3:
    build: .
    volumes:
      - .:/opt/server/
    command: [ "python", "-u", "/opt/server/tinyblockchain/app.py", "--config-file", "/opt/server/config/node3.yaml"]
    ports:
      - "5003:5003"
    networks:
      - backend
    depends_on:
      - node2

networks:
  backend:
